// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Quantity       int32
	Status         interface{}
	Description    string
	CreatedAt      time.Time
	ProductPriceID uuid.UUID
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Stock       int32
	IsService   bool
	Description string
	Image       string
	CreatedAt   time.Time
}

type ProductPrice struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	Price         int32
	EffectiveDate time.Time
	CreatedAt     time.Time
}

type ProductStock struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	SupplierID uuid.UUID
	IsAdd      bool
	Quantity   int32
	Price      int32
	CreatedAt  time.Time
}

type Supplier struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	Address      string
	Phone        string
	CreatedAt    time.Time
}
