// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_stocks.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getProductStocksByProductId = `-- name: GetProductStocksByProductId :many
SELECT id, product_id, supplier_id, is_add, quantity, price, created_at FROM product_stocks WHERE product_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetProductStocksByProductId(ctx context.Context, productID uuid.UUID) ([]ProductStock, error) {
	rows, err := q.db.QueryContext(ctx, getProductStocksByProductId, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductStock
	for rows.Next() {
		var i ProductStock
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SupplierID,
			&i.IsAdd,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProductStock = `-- name: InsertProductStock :execresult
INSERT INTO product_stocks (
  product_id, supplier_id, is_add, quantity, price
) VALUES (
  $1, $2, $3, $4, $5
)
`

type InsertProductStockParams struct {
	ProductID  uuid.UUID
	SupplierID uuid.UUID
	IsAdd      bool
	Quantity   int32
	Price      int32
}

func (q *Queries) InsertProductStock(ctx context.Context, arg InsertProductStockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProductStock,
		arg.ProductID,
		arg.SupplierID,
		arg.IsAdd,
		arg.Quantity,
		arg.Price,
	)
}
