// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateSupplier(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createSupplier, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
DELETE FROM suppliers WHERE id = $1
`

func (q *Queries) DeleteSupplier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSupplier, id)
	return err
}

const getSupplierById = `-- name: GetSupplierById :one
SELECT id, name, created_at FROM suppliers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSupplierById(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, getSupplierById, id)
	var i Supplier
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getSuppliers = `-- name: GetSuppliers :many
SELECT id, name, created_at FROM suppliers ORDER BY name ASC
`

func (q *Queries) GetSuppliers(ctx context.Context) ([]Supplier, error) {
	rows, err := q.db.QueryContext(ctx, getSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
